// <auto-generated />
using EmpleadosApp.Server.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmpleadosApp.Server.Migrations
{
    [DbContext(typeof(EmpleadosDbContext))]
    [Migration("20260825162312_Seedeer")]
    partial class Seedeer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmpleadosApp.Server.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Tecnologías de la Información"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Finanzas"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ventas"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Operaciones"
                        });
                });

            modelBuilder.Entity("EmpleadosApp.Server.Entities.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("PuestoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Empleados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Juan Pérez",
                            PuestoId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "María López",
                            PuestoId = 2,
                            UsuarioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Carlos García",
                            PuestoId = 3,
                            UsuarioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Ana Martínez",
                            PuestoId = 4,
                            UsuarioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Luis Hernández",
                            PuestoId = 5,
                            UsuarioId = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Pedro González",
                            PuestoId = 3,
                            UsuarioId = 6
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Laura Ramírez",
                            PuestoId = 4,
                            UsuarioId = 7
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "José Torres",
                            PuestoId = 5,
                            UsuarioId = 8
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Sofía Flores",
                            PuestoId = 3,
                            UsuarioId = 9
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Miguel Sánchez",
                            PuestoId = 2,
                            UsuarioId = 10
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Daniel Rodríguez",
                            PuestoId = 3,
                            UsuarioId = 11
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Fernanda Cruz",
                            PuestoId = 4,
                            UsuarioId = 12
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Ricardo Morales",
                            PuestoId = 5,
                            UsuarioId = 13
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Gabriela Ortiz",
                            PuestoId = 3,
                            UsuarioId = 14
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Alejandro Vargas",
                            PuestoId = 2,
                            UsuarioId = 15
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Patricia Mendoza",
                            PuestoId = 4,
                            UsuarioId = 16
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Roberto Castro",
                            PuestoId = 5,
                            UsuarioId = 17
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Andrea Ruiz",
                            PuestoId = 3,
                            UsuarioId = 18
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Jorge Navarro",
                            PuestoId = 4,
                            UsuarioId = 19
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Diana Reyes",
                            PuestoId = 5,
                            UsuarioId = 20
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Eduardo Jiménez",
                            PuestoId = 3,
                            UsuarioId = 21
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Claudia Moreno",
                            PuestoId = 4,
                            UsuarioId = 22
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Francisco Silva",
                            PuestoId = 5,
                            UsuarioId = 23
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Mónica Ríos",
                            PuestoId = 3,
                            UsuarioId = 24
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Héctor Guerrero",
                            PuestoId = 2,
                            UsuarioId = 25
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Natalia Medina",
                            PuestoId = 4,
                            UsuarioId = 26
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Sergio Peña",
                            PuestoId = 5,
                            UsuarioId = 27
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Valeria Campos",
                            PuestoId = 3,
                            UsuarioId = 28
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Oscar Fuentes",
                            PuestoId = 4,
                            UsuarioId = 29
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Regina Cabrera",
                            PuestoId = 5,
                            UsuarioId = 30
                        },
                        new
                        {
                            Id = 31,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Arturo León",
                            PuestoId = 3,
                            UsuarioId = 31
                        },
                        new
                        {
                            Id = 32,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Mariana Soto",
                            PuestoId = 4,
                            UsuarioId = 32
                        },
                        new
                        {
                            Id = 33,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Enrique Paredes",
                            PuestoId = 5,
                            UsuarioId = 33
                        },
                        new
                        {
                            Id = 34,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Lucía Velázquez",
                            PuestoId = 3,
                            UsuarioId = 34
                        },
                        new
                        {
                            Id = 35,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Alberto Márquez",
                            PuestoId = 2,
                            UsuarioId = 35
                        },
                        new
                        {
                            Id = 36,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Camila Espinoza",
                            PuestoId = 4,
                            UsuarioId = 36
                        },
                        new
                        {
                            Id = 37,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Martín Salazar",
                            PuestoId = 5,
                            UsuarioId = 37
                        },
                        new
                        {
                            Id = 38,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Alejandra Núñez",
                            PuestoId = 3,
                            UsuarioId = 38
                        },
                        new
                        {
                            Id = 39,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Gustavo Acosta",
                            PuestoId = 4,
                            UsuarioId = 39
                        },
                        new
                        {
                            Id = 40,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Paola Miranda",
                            PuestoId = 5,
                            UsuarioId = 40
                        },
                        new
                        {
                            Id = 41,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Manuel Rojas",
                            PuestoId = 3,
                            UsuarioId = 41
                        },
                        new
                        {
                            Id = 42,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Elena Valdez",
                            PuestoId = 4,
                            UsuarioId = 42
                        },
                        new
                        {
                            Id = 43,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Rafael Lozano",
                            PuestoId = 5,
                            UsuarioId = 43
                        },
                        new
                        {
                            Id = 44,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Silvia Ibarra",
                            PuestoId = 3,
                            UsuarioId = 44
                        },
                        new
                        {
                            Id = 45,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Tomás Estrada",
                            PuestoId = 2,
                            UsuarioId = 45
                        },
                        new
                        {
                            Id = 46,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Verónica Ponce",
                            PuestoId = 4,
                            UsuarioId = 46
                        },
                        new
                        {
                            Id = 47,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Javier Beltrán",
                            PuestoId = 5,
                            UsuarioId = 47
                        },
                        new
                        {
                            Id = 48,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Carolina Orozco",
                            PuestoId = 3,
                            UsuarioId = 48
                        },
                        new
                        {
                            Id = 49,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Raúl Domínguez",
                            PuestoId = 4,
                            UsuarioId = 49
                        },
                        new
                        {
                            Id = 50,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Beatriz Carrillo",
                            PuestoId = 5,
                            UsuarioId = 50
                        },
                        new
                        {
                            Id = 51,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Iván Miranda",
                            PuestoId = 3,
                            UsuarioId = 51
                        },
                        new
                        {
                            Id = 52,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Melissa Aguirre",
                            PuestoId = 4,
                            UsuarioId = 52
                        },
                        new
                        {
                            Id = 53,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Mauricio Valencia",
                            PuestoId = 5,
                            UsuarioId = 53
                        },
                        new
                        {
                            Id = 54,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Adriana Nieto",
                            PuestoId = 3,
                            UsuarioId = 54
                        },
                        new
                        {
                            Id = 55,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Salvador Zamora",
                            PuestoId = 2,
                            UsuarioId = 55
                        },
                        new
                        {
                            Id = 56,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Karen Castañeda",
                            PuestoId = 4,
                            UsuarioId = 56
                        },
                        new
                        {
                            Id = 57,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Víctor Rocha",
                            PuestoId = 5,
                            UsuarioId = 57
                        },
                        new
                        {
                            Id = 58,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Isabel Franco",
                            PuestoId = 3,
                            UsuarioId = 58
                        },
                        new
                        {
                            Id = 59,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Gerardo Solís",
                            PuestoId = 4,
                            UsuarioId = 59
                        },
                        new
                        {
                            Id = 60,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Renata Márquez",
                            PuestoId = 5,
                            UsuarioId = 60
                        },
                        new
                        {
                            Id = 61,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Cristian Luna",
                            PuestoId = 3,
                            UsuarioId = 61
                        },
                        new
                        {
                            Id = 62,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Paulina Rosales",
                            PuestoId = 4,
                            UsuarioId = 62
                        },
                        new
                        {
                            Id = 63,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Esteban Valencia",
                            PuestoId = 5,
                            UsuarioId = 63
                        },
                        new
                        {
                            Id = 64,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Jimena Padilla",
                            PuestoId = 3,
                            UsuarioId = 64
                        },
                        new
                        {
                            Id = 65,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Ángel Miranda",
                            PuestoId = 2,
                            UsuarioId = 65
                        },
                        new
                        {
                            Id = 66,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Fabiola Sandoval",
                            PuestoId = 4,
                            UsuarioId = 66
                        },
                        new
                        {
                            Id = 67,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Rodrigo Mejía",
                            PuestoId = 5,
                            UsuarioId = 67
                        },
                        new
                        {
                            Id = 68,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Cecilia Bravo",
                            PuestoId = 3,
                            UsuarioId = 68
                        },
                        new
                        {
                            Id = 69,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Nicolás Ortega",
                            PuestoId = 4,
                            UsuarioId = 69
                        },
                        new
                        {
                            Id = 70,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Teresa Salgado",
                            PuestoId = 5,
                            UsuarioId = 70
                        },
                        new
                        {
                            Id = 71,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Emiliano Lara",
                            PuestoId = 3,
                            UsuarioId = 71
                        },
                        new
                        {
                            Id = 72,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Bárbara Cortés",
                            PuestoId = 4,
                            UsuarioId = 72
                        },
                        new
                        {
                            Id = 73,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Adrián Villanueva",
                            PuestoId = 5,
                            UsuarioId = 73
                        },
                        new
                        {
                            Id = 74,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Lorena Cárdenas",
                            PuestoId = 3,
                            UsuarioId = 74
                        },
                        new
                        {
                            Id = 75,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Diego Valenzuela",
                            PuestoId = 2,
                            UsuarioId = 75
                        },
                        new
                        {
                            Id = 76,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Montserrat Arias",
                            PuestoId = 4,
                            UsuarioId = 76
                        },
                        new
                        {
                            Id = 77,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Jesús Rangel",
                            PuestoId = 5,
                            UsuarioId = 77
                        },
                        new
                        {
                            Id = 78,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Marisol Bautista",
                            PuestoId = 3,
                            UsuarioId = 78
                        },
                        new
                        {
                            Id = 79,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Ignacio Franco",
                            PuestoId = 4,
                            UsuarioId = 79
                        },
                        new
                        {
                            Id = 80,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Ximena Escobar",
                            PuestoId = 5,
                            UsuarioId = 80
                        },
                        new
                        {
                            Id = 81,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Bruno Serrano",
                            PuestoId = 3,
                            UsuarioId = 81
                        },
                        new
                        {
                            Id = 82,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Regina Maldonado",
                            PuestoId = 4,
                            UsuarioId = 82
                        },
                        new
                        {
                            Id = 83,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Mateo Delgado",
                            PuestoId = 5,
                            UsuarioId = 83
                        },
                        new
                        {
                            Id = 84,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Elisa Rosas",
                            PuestoId = 3,
                            UsuarioId = 84
                        },
                        new
                        {
                            Id = 85,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Leonardo Miranda",
                            PuestoId = 2,
                            UsuarioId = 85
                        },
                        new
                        {
                            Id = 86,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Daniela Nieto",
                            PuestoId = 4,
                            UsuarioId = 86
                        },
                        new
                        {
                            Id = 87,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Pablo Cisneros",
                            PuestoId = 5,
                            UsuarioId = 87
                        },
                        new
                        {
                            Id = 88,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Sara Coronado",
                            PuestoId = 3,
                            UsuarioId = 88
                        },
                        new
                        {
                            Id = 89,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Fernando Olivares",
                            PuestoId = 4,
                            UsuarioId = 89
                        },
                        new
                        {
                            Id = 90,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Natalia Rosales",
                            PuestoId = 5,
                            UsuarioId = 90
                        },
                        new
                        {
                            Id = 91,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Marco Antonio Ruiz",
                            PuestoId = 3,
                            UsuarioId = 91
                        },
                        new
                        {
                            Id = 92,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "Julia Medina",
                            PuestoId = 4,
                            UsuarioId = 92
                        },
                        new
                        {
                            Id = 93,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Ramón Cabrera",
                            PuestoId = 5,
                            UsuarioId = 93
                        },
                        new
                        {
                            Id = 94,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Estefanía León",
                            PuestoId = 3,
                            UsuarioId = 94
                        },
                        new
                        {
                            Id = 95,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Guillermo Ríos",
                            PuestoId = 2,
                            UsuarioId = 95
                        },
                        new
                        {
                            Id = 96,
                            Activo = true,
                            DepartamentoId = 1,
                            Nombre = "Abril Hernández",
                            PuestoId = 4,
                            UsuarioId = 96
                        },
                        new
                        {
                            Id = 97,
                            Activo = true,
                            DepartamentoId = 4,
                            Nombre = "Samuel Pacheco",
                            PuestoId = 5,
                            UsuarioId = 97
                        },
                        new
                        {
                            Id = 98,
                            Activo = true,
                            DepartamentoId = 2,
                            Nombre = "Rosa Elena Vargas",
                            PuestoId = 3,
                            UsuarioId = 98
                        },
                        new
                        {
                            Id = 99,
                            Activo = true,
                            DepartamentoId = 3,
                            Nombre = "César Montoya",
                            PuestoId = 4,
                            UsuarioId = 99
                        },
                        new
                        {
                            Id = 100,
                            Activo = true,
                            DepartamentoId = 5,
                            Nombre = "Karla Méndez",
                            PuestoId = 5,
                            UsuarioId = 100
                        });
                });

            modelBuilder.Entity("EmpleadosApp.Server.Entities.Proyectos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("EmpleadosApp.Server.Entities.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Puestos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Gerente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Supervisor"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Desarrollador"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Analista"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Asistente"
                        });
                });

            modelBuilder.Entity("EmpleadosApp.Server.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "María López"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Carlos García"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Ana Martínez"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Luis Hernández"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Pedro González"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Laura Ramírez"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "José Torres"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Sofía Flores"
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Miguel Sánchez"
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Daniel Rodríguez"
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "Fernanda Cruz"
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Ricardo Morales"
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Gabriela Ortiz"
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Alejandro Vargas"
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Patricia Mendoza"
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Roberto Castro"
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Andrea Ruiz"
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Jorge Navarro"
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Diana Reyes"
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Eduardo Jiménez"
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Claudia Moreno"
                        },
                        new
                        {
                            Id = 23,
                            Nombre = "Francisco Silva"
                        },
                        new
                        {
                            Id = 24,
                            Nombre = "Mónica Ríos"
                        },
                        new
                        {
                            Id = 25,
                            Nombre = "Héctor Guerrero"
                        },
                        new
                        {
                            Id = 26,
                            Nombre = "Natalia Medina"
                        },
                        new
                        {
                            Id = 27,
                            Nombre = "Sergio Peña"
                        },
                        new
                        {
                            Id = 28,
                            Nombre = "Valeria Campos"
                        },
                        new
                        {
                            Id = 29,
                            Nombre = "Oscar Fuentes"
                        },
                        new
                        {
                            Id = 30,
                            Nombre = "Regina Cabrera"
                        },
                        new
                        {
                            Id = 31,
                            Nombre = "Arturo León"
                        },
                        new
                        {
                            Id = 32,
                            Nombre = "Mariana Soto"
                        },
                        new
                        {
                            Id = 33,
                            Nombre = "Enrique Paredes"
                        },
                        new
                        {
                            Id = 34,
                            Nombre = "Lucía Velázquez"
                        },
                        new
                        {
                            Id = 35,
                            Nombre = "Alberto Márquez"
                        },
                        new
                        {
                            Id = 36,
                            Nombre = "Camila Espinoza"
                        },
                        new
                        {
                            Id = 37,
                            Nombre = "Martín Salazar"
                        },
                        new
                        {
                            Id = 38,
                            Nombre = "Alejandra Núñez"
                        },
                        new
                        {
                            Id = 39,
                            Nombre = "Gustavo Acosta"
                        },
                        new
                        {
                            Id = 40,
                            Nombre = "Paola Miranda"
                        },
                        new
                        {
                            Id = 41,
                            Nombre = "Manuel Rojas"
                        },
                        new
                        {
                            Id = 42,
                            Nombre = "Elena Valdez"
                        },
                        new
                        {
                            Id = 43,
                            Nombre = "Rafael Lozano"
                        },
                        new
                        {
                            Id = 44,
                            Nombre = "Silvia Ibarra"
                        },
                        new
                        {
                            Id = 45,
                            Nombre = "Tomás Estrada"
                        },
                        new
                        {
                            Id = 46,
                            Nombre = "Verónica Ponce"
                        },
                        new
                        {
                            Id = 47,
                            Nombre = "Javier Beltrán"
                        },
                        new
                        {
                            Id = 48,
                            Nombre = "Carolina Orozco"
                        },
                        new
                        {
                            Id = 49,
                            Nombre = "Raúl Domínguez"
                        },
                        new
                        {
                            Id = 50,
                            Nombre = "Beatriz Carrillo"
                        },
                        new
                        {
                            Id = 51,
                            Nombre = "Iván Miranda"
                        },
                        new
                        {
                            Id = 52,
                            Nombre = "Melissa Aguirre"
                        },
                        new
                        {
                            Id = 53,
                            Nombre = "Mauricio Valencia"
                        },
                        new
                        {
                            Id = 54,
                            Nombre = "Adriana Nieto"
                        },
                        new
                        {
                            Id = 55,
                            Nombre = "Salvador Zamora"
                        },
                        new
                        {
                            Id = 56,
                            Nombre = "Karen Castañeda"
                        },
                        new
                        {
                            Id = 57,
                            Nombre = "Víctor Rocha"
                        },
                        new
                        {
                            Id = 58,
                            Nombre = "Isabel Franco"
                        },
                        new
                        {
                            Id = 59,
                            Nombre = "Gerardo Solís"
                        },
                        new
                        {
                            Id = 60,
                            Nombre = "Renata Márquez"
                        },
                        new
                        {
                            Id = 61,
                            Nombre = "Cristian Luna"
                        },
                        new
                        {
                            Id = 62,
                            Nombre = "Paulina Rosales"
                        },
                        new
                        {
                            Id = 63,
                            Nombre = "Esteban Valencia"
                        },
                        new
                        {
                            Id = 64,
                            Nombre = "Jimena Padilla"
                        },
                        new
                        {
                            Id = 65,
                            Nombre = "Ángel Miranda"
                        },
                        new
                        {
                            Id = 66,
                            Nombre = "Fabiola Sandoval"
                        },
                        new
                        {
                            Id = 67,
                            Nombre = "Rodrigo Mejía"
                        },
                        new
                        {
                            Id = 68,
                            Nombre = "Cecilia Bravo"
                        },
                        new
                        {
                            Id = 69,
                            Nombre = "Nicolás Ortega"
                        },
                        new
                        {
                            Id = 70,
                            Nombre = "Teresa Salgado"
                        },
                        new
                        {
                            Id = 71,
                            Nombre = "Emiliano Lara"
                        },
                        new
                        {
                            Id = 72,
                            Nombre = "Bárbara Cortés"
                        },
                        new
                        {
                            Id = 73,
                            Nombre = "Adrián Villanueva"
                        },
                        new
                        {
                            Id = 74,
                            Nombre = "Lorena Cárdenas"
                        },
                        new
                        {
                            Id = 75,
                            Nombre = "Diego Valenzuela"
                        },
                        new
                        {
                            Id = 76,
                            Nombre = "Montserrat Arias"
                        },
                        new
                        {
                            Id = 77,
                            Nombre = "Jesús Rangel"
                        },
                        new
                        {
                            Id = 78,
                            Nombre = "Marisol Bautista"
                        },
                        new
                        {
                            Id = 79,
                            Nombre = "Ignacio Franco"
                        },
                        new
                        {
                            Id = 80,
                            Nombre = "Ximena Escobar"
                        },
                        new
                        {
                            Id = 81,
                            Nombre = "Bruno Serrano"
                        },
                        new
                        {
                            Id = 82,
                            Nombre = "Regina Maldonado"
                        },
                        new
                        {
                            Id = 83,
                            Nombre = "Mateo Delgado"
                        },
                        new
                        {
                            Id = 84,
                            Nombre = "Elisa Rosas"
                        },
                        new
                        {
                            Id = 85,
                            Nombre = "Leonardo Miranda"
                        },
                        new
                        {
                            Id = 86,
                            Nombre = "Daniela Nieto"
                        },
                        new
                        {
                            Id = 87,
                            Nombre = "Pablo Cisneros"
                        },
                        new
                        {
                            Id = 88,
                            Nombre = "Sara Coronado"
                        },
                        new
                        {
                            Id = 89,
                            Nombre = "Fernando Olivares"
                        },
                        new
                        {
                            Id = 90,
                            Nombre = "Natalia Rosales"
                        },
                        new
                        {
                            Id = 91,
                            Nombre = "Marco Antonio Ruiz"
                        },
                        new
                        {
                            Id = 92,
                            Nombre = "Julia Medina"
                        },
                        new
                        {
                            Id = 93,
                            Nombre = "Ramón Cabrera"
                        },
                        new
                        {
                            Id = 94,
                            Nombre = "Estefanía León"
                        },
                        new
                        {
                            Id = 95,
                            Nombre = "Guillermo Ríos"
                        },
                        new
                        {
                            Id = 96,
                            Nombre = "Abril Hernández"
                        },
                        new
                        {
                            Id = 97,
                            Nombre = "Samuel Pacheco"
                        },
                        new
                        {
                            Id = 98,
                            Nombre = "Rosa Elena Vargas"
                        },
                        new
                        {
                            Id = 99,
                            Nombre = "César Montoya"
                        },
                        new
                        {
                            Id = 100,
                            Nombre = "Karla Méndez"
                        });
                });

            modelBuilder.Entity("EmpleadosApp.Server.Entities.Empleado", b =>
                {
                    b.HasOne("EmpleadosApp.Server.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpleadosApp.Server.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmpleadosApp.Server.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Puesto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EmpleadosApp.Server.Entities.Proyectos", b =>
                {
                    b.HasOne("EmpleadosApp.Server.Entities.Empleado", null)
                        .WithMany("Proyectos")
                        .HasForeignKey("EmpleadoId");
                });

            modelBuilder.Entity("EmpleadosApp.Server.Entities.Empleado", b =>
                {
                    b.Navigation("Proyectos");
                });
#pragma warning restore 612, 618
        }
    }
}
